const config = [
    {
        files: ['**/*.ts', '**/*.tsx'], // Changed from ['**/*.js', '**/*.tsx']
        ignores: ['**/node_modules/**', '**/build/**', '**/*.d.ts', '**/types/**'],
        languageOptions: {
            parser: require('@typescript-eslint/parser'),
            parserOptions: {
                ecmaVersion: 2019,
                project: './tsconfig.json',
                tsconfigRootDir: '.',
            },
        },
        plugins: {
            '@typescript-eslint': require('typescript-eslint'),
        },
        rules: {
            'max-len': ['error', {code: 140, comments: 180}],
            'block-spacing': ['error', 'always'],
            'space-before-function-paren': ['error', {anonymous: 'always', named: 'never'}],
            'space-in-parens': ['error', 'never'],
            'object-curly-spacing': ['error', 'never'],
            'lines-between-class-members': ['error', 'always', {exceptAfterSingleLine: true}],
            'arrow-spacing': ['error', {before: true, after: true}],
            'array-bracket-spacing': ['error', 'never'],
            'computed-property-spacing': ['error', 'never'],
            'template-curly-spacing': ['error', 'never'],
            'object-property-newline': ['off', {allowMultiplePropertiesPerLine: true}],
            'quotes': ['error', 'single', {avoidEscape: true}],
            'no-unused-vars': 'off',
            '@typescript-eslint/no-unused-vars': ['off'],
            'no-control-regex': 'off',
            'complexity': ['warn', {max: 4}],
            'prefer-const': ['off'],
            'no-plusplus': ['off'],
            'no-extra-boolean-cast': ['off'],
            'no-prototype-builtins': ['off'],
            'no-useless-escape': ['off'],
            'no-empty-pattern': ['off'],
            '@typescript-eslint/no-unsafe-member-access': ['off'],
            '@typescript-eslint/no-inferrable-types': ['off'],
            '@typescript-eslint/ban-types': ['off'],
            '@typescript-eslint/no-unsafe-return': ['off'],
            '@typescript-eslint/no-unsafe-assignment': ['off'],
            '@typescript-eslint/no-unsafe-call': ['off'],
            '@typescript-eslint/no-floating-promises': ['off'],
            '@typescript-eslint/restrict-plus-operands': ['off'],
            '@typescript-eslint/no-implied-eval': ['off'],
            '@typescript-eslint/no-empty-function': ['off'],
            '@typescript-eslint/no-empty-interface': ['off'],
            '@typescript-eslint/explicit-function-return-type': ['off'],
            'comma-dangle': ['off'],
            '@typescript-eslint/member-ordering': ['off'],
            'spaced-comment': ['off'],
            '@typescript-eslint/no-use-before-define': ['off'],
            '@typescript-eslint/unbound-method': ['off'],
        },
    },
    {
        files: ['**/*.js'],
        ignores: ['node_modules/', '**/build/**'],
        languageOptions: {
            ecmaVersion: 2019,
        },
        rules: {
            'max-len': ['error', {code: 140, comments: 180}],
            'block-spacing': ['error', 'always'],
            'space-before-function-paren': ['error', {anonymous: 'always', named: 'never'}],
            'space-in-parens': ['error', 'never'],
            'object-curly-spacing': ['error', 'never'],
            'lines-between-class-members': ['error', 'always', {exceptAfterSingleLine: true}],
            'arrow-spacing': ['error', {before: true, after: true}],
            'array-bracket-spacing': ['error', 'never'],
            'computed-property-spacing': ['error', 'never'],
            'template-curly-spacing': ['error', 'never'],
            'object-property-newline': ['off', {allowMultiplePropertiesPerLine: true}],
            'quotes': ['error', 'single', {avoidEscape: true}],
            'semi': ['error', 'always'],
            'no-control-regex': 'off',
        },
    },
];

module.exports = config;
