= Guillotine application

Once assigned to your site, 
the guillotine application will generate a dynamic GraphQL API that enables web-based access to all your editorial content.

Guillotine exposes the read-only part of the Enonic Content API, including access to the Enonic query language. 
Guillotine dynamically analyzes all available content types in the site and generates a GraphQL API specific to your site. 
This gives you direct, typed and documented access to all content within the site. Including the ability to follow references, 
child items and access media directly.

== Compatibility

[cols="1,1,3", options="header"]
|===
|Version 
|Min.XP Version
|Download

|4.1.0
|7.0.0
|http://repo.enonic.com/public/com/enonic/app/guillotine/4.0.0/guillotine-4.1.0.jar[Download]

|4.0.0
|7.0.0
|http://repo.enonic.com/public/com/enonic/app/guillotine/4.0.0/guillotine-4.0.0.jar[Download]

|3.0.0
|7.0.0
|http://repo.enonic.com/public/com/enonic/app/guillotine/3.0.0/guillotine-3.0.0.jar[Download]

|2.0.0
|7.0.0
|http://repo.enonic.com/public/com/enonic/app/guillotine/2.0.0/guillotine-2.0.0.jar[Download]

|1.0.0
|6.13.0
|http://repo.enonic.com/public/com/enonic/app/guillotine/1.0.0/guillotine-1.0.0.jar[Download]

|0.2.0
|6.13.0
|http://repo.enonic.com/public/com/enonic/app/guillotine/0.2.0/guillotine-0.2.0.jar[Download]

|0.1.5
|6.10.0
|http://repo.enonic.com/public/com/enonic/app/guillotine/0.1.5/guillotine-0.1.5.jar[Download]
|===

== Breaking changes

=== Breaking changes in 4.0

- Type "Content": Field "page": Removed (Use fields "pageAsJson" or "components" instead)
- Types "Flat*Component*": Renamed to "*Component*".
- Type "FlatDescriptorBasedComponentData": Split into 2 types: "LayoutComponentData" and "PartComponentData"
- Fields "config": Renamed to "configAsJson"
- Type "Content": Field "components": By default, the components of the page template are used instead if there is one.
- Type "Content": Field "components": By default, the fragments are inlined

=== Breaking changes in 3.0

- Type "Content": Fields "creator", "modifier", "owner" and "permissions" need one of the following roles: "cms.cm.app", "cms.admin" or "system.admin"

=== Breaking changes in 2.0

- Type "PrincipalKey": Field "userStore" renamed to "idProvider"
- Type "Page": Field "controller" renamed to "descriptor"
- Type "Component": Field "name" removed

== Build

To build this project, execute the following:

[source,bash]
----
./gradlew clean build
----

== link:docs/index.adoc[Documentation]
