query {
    guillotine {
        attachmentUrl: get(key: "contentid") {
            ... on media_Image {
                mediaUrl(params: {
                    a: 1,
                    b: [2, 3],
                    c: []
                }) {
                    apiUrl
                    path
                    queryString
                    intent
                }
            }
        }
        downloadAttachmentUrl: get(key: "contentid") {
            ... on media_Image {
                mediaUrl(download: true) {
                    queryString
                    intent
                }
            }
        }
    }
}
