= GraphQL API Documentation
:toc: left

This documentation describes all static GraphQL types

.Common arguments
* key: Designs a content path or content ID
* offset: Start index. Default: 0
* first: Number of content to fetch. Default: 10
* sort: Sorting expression. Default: "_score DESC"

== Query 
* Fields
** content: ContentAPI

== ContentAPI 
Contains all requests to retrieve contents. 

Most requests expect a key as argument. 
If the key is not specified, then the matched content will be the one corresponding to the current execution context

* Fields
** get(key: ID): Content
+
Fetches a content

** getChildren(
key: ID
offset: Int
first: Int
sort: String
): [Content]
+
Fetches the children of a content

** getChildrenConnection(
key: ID
after: String
first: Int
sort: String
): ContentConnection
+
Fetches the children of a content and return the result as a connection

** getPermissions(key: ID): Permissions
+
Fetches the permissions on a content

** getSite: portal_Site
+
Fetches the parent site of the content corresponding to the current execution context

** query(
query: String
offset: Int
first: Int
sort: String
contentTypes: [String]
): [Content]
+
Queries contents

** queryConnection(
query: String!
after: String
first: Int
sort: String
contentTypes: [String]
): ContentConnection
+
Queries contents and returns the result as a connection

** getType(name: String!): ContentType
+
Retrieves the properties and icon of the specified content type

** getTypes: [ContentType]
+
Retrieves the list of all content types available for the current site

