= Guillotine 7 - GraphQL API for Enonic XP
A bend-over-backwards flexible GraphQL API based on XP's content API

== Introduction

TIP: *Quickstart!* Check out https://developer.enonic.com/docs/developer-101[the Developer 101 tutorial] for a hands-on introduction to Enonic and the Guillotine API.

Guillotine is at the essence a strongly typed GraphQL read-only version of XP's internal https://developer.enonic.com/docs/xp/stable/api/lib-content[JS Content API]. 

== Query Playground

Guillotine extends Content Studio, allowing privileged users to <<query-playground#, query the API in context of their content>>.

== Query examples

A basic introduction to using the API, with hands on example queries.

Learn more about <<query-examples.adoc#,how to use the API>>.

== Command line and JavaScript

Examples on how to invoke the API using <<usage/curl#, cURL>> or <<usage/javascript#, JavaScript>>.

Learn more about GraphQL and how to <<clients#,invoke the API from different clients>>.

== Extending

Guillotine's superpower lies in the ability to dynamically extend and augment the API to match the requirements of your digital experiences and front-ends.

Learn more about <<extending#,extending the API>>.
