= Guillotine project

Guillotine turns Enonic XP into a headless CMS by adding a GraphQL content API to the platform.

TIP: *Quickstart!* For a quick intro to basic use of Guillotine, check out https://developer.enonic.com/docs/headless-cms-intro[Headless CMS intro].

== Introduction
Guillotine is available on https://market.enonic.com/vendors/enonic/guillotine-headless-cms[Enonic Market].

The application provides a strongly typed GraphQL read-only version of XP's https://developer.enonic.com/docs/xp/stable/api/lib-content[JavaScript Content API], as well as an extension to Content Studio that allows privileged users to run test the API.

== Usage

Developers, and super users may instantly test the API via a Content Studio extension called `Query playground`, which is included in the Guillotine application.

Learn more about GraphQL and <<usage#,how to use the API>>

== Endpoints

Guillotine automatically provisions endpoints for public access to the API. 

Learn more about <<endpoints#,accessing the endpoints>>

== GraphQL API

Guillotine provides a set of standard fields like `get` and `query`. Additionally, it dynamically generates GraphQL Types based on the schemas (content types, components etc) registered in your Enonic instance.

Learn more about the standard types of the <<api#,API>>

== Rich text processing

Details related to <<rich-text#,Rich text handling>> in Guillotine.

== Embedding

Guillotine is also available in a library version, which for advanced use-cases may be embedded into your app. It lets you take control over the endpoints, detailed access control, as well as ability to extend and customise the API itself.

<<embed#, Read more about integrating and customizing the Guillotine API>>