= Project Guillotine 7

Guillotine turns Enonic XP into a headless CMS by adding a GraphQL content API on top of every content project

TIP: *Quickstart!* For hands on usage of Enonic XP, check out https://developer.enonic.com/docs/developer-101[the Developer 101 tutorial].

== Introduction
Guillotine is available as an application on https://market.enonic.com/vendors/enonic/guillotine-headless-cms[Enonic Market]!

The Guillotine API is essentially a strongly typed GraphQL read-only version of XP's internal https://developer.enonic.com/docs/xp/stable/api/lib-content[JS Content API]. In addition to the API, Guillotine adds a new panel to Content Studio, allowing privileged users to query the API in context of their content.

== Endpoints

Guillotine automatically provisions endpoints to access the API.

Learn how to <<endpoints#,access the API>>

== Query examples

A basic introduction to using the API, with hands on example queries.

Learn more about <<query-examples.adoc#,how to use the API>>.


== Clients

How to invoke the API from Content Studio, via cURL, or from JavaScript.

Learn more about GraphQL and how to <<clients#,invoke the API from different clients>>.


== GraphQL API

Guillotine provides a set of standard fields, but also dynamically generates GraphQL Types based on the installed schemas.

Learn more about the <<api#,standard schema types>>.

== Extending

Guillotine allows you to extend the API with custom fields, types and more.

Learn more about <<extending#,extending the API>>.
