= Release Notes

== Guillotine 6 Update 2

=== Release features

- Upgrade GraphiQL to version 2.x.
- Make Query Playground available on GET `/site/<repo>` endpoint.

== Guillotine 6 Update 1

=== Release features

Query DSL and Highlight::
* Deprecated fields `query` and `queryConnection` in <<api#fields_2, Query type>> are replaced with `queryDsl` and `queryDslConnection` for DSL expressions.
* Added new input types for <<api#query_dsl_input_types, Query DSL>> and <<api#highlight_input_types, Highlight>>
* Added new <<api#enum_types, Enum types>> for DSL and Highlight


=== Deprecations
`query` and `queryConnection` fields in <<api#fields_2, Query type>> are deprecated and will be removed in Guillotine 7.

== Guillotine 6

WARNING: This release includes <<breaking_changes, breaking changes>>

=== Release features

Project level API:: The Guillotine app now mounts to the root of all projects - automatically provisioning an API to all project branches root i.e. `/site/<myproject>/<branch>`.

Dynamic site context:: With the API now being project-relative, setting the site context in a header enable you to <<usage#site_context, perform site relative queries>>.

Global schema:: The GraphQL type schema is generated from all available schemas (across all installed apps) in the Enonic instance.

Content Studio API browser:: Guillotine also features an embedded GraphQL API browser called <<clients#query_playground, Query playground>>. Query Playground is available directly in Content Studio, in context of your projects.

Typed x-data schemas:: Like for all other schemas, x-data are now also fully typed - grouped by application key. See <<usage#xdata, examples of xData usage>>

=== Breaking changes

Site deployment removed:: You may no longer add this application to a site, and get a contextual API. Use the <<usage#site_context, site context header>>, or <<embed#, embed Guillotine>> in your application to replicate this functionality.

ItemSet and OptionSet type name fix:: Previously, their types were erroneously generated from their schema label, rather than name. Clients using these types through introspection will break if label and name are different in the schemas.
