= Setting up Guillotine

This section describes how to install and access the Guillotine API

== Requirements

IMPORTANT: Guillotine 9 requires Enonic XP 8.1.0 or higher.

== Installation

Guillotine is available as an Enonic app. Guillotine will normally be pre-installed when you create a new solution in the self-service cloud, or when setting up a new SDK Sandbox.

To install it manually, follow the https://market.enonic.com/vendors/enonic/guillotine[instructions on Enonic Market].

== Endpoints

Guillotine exposes its GraphQL API as an https://developer.enonic.com/docs/code/stable/web/apis[XP API] named `com.enonic.app.guillotine:graphql`. Once installed, it is available on the API endpoint of your Enonic instance:

* HTTP POST `:8080/api/com.enonic.app.guillotine:graphql`

The endpoint accepts a JSON body with a mandatory `query` string and an optional `variables` object, and answers `POST` and `OPTIONS` requests only. Access to content is controlled by content permissions: unauthenticated requests only see content readable by `system.everyone`.

=== Project and branch

A single endpoint serves all content projects. The project and branch (`draft` or `master`) are selected with the `project` and `branch` arguments of the `guillotine` field:

[source,graphql]
----
{
  guillotine(project: "myproject", branch: "master") {
    getChildren(key: "/") {
      displayName
    }
  }
}
----

If the arguments are omitted, the project and branch of the request context are used. On the `/api` endpoint you should therefore always pass `project`; `branch` may alternatively be given as the `branch` request parameter, e.g. `/api/com.enonic.app.guillotine:graphql?branch=draft`.

NOTE: When the API is invoked in the context of a site or from Content Studio (see below), the project and branch are defined by that context and the `project`/`branch` arguments are ignored.

=== Mounting the API in a site

The API can also be mounted inside a site, so that queries run in the context of that site. Add the API to the `apis` list of your site descriptor:

.site.yaml
[source,yaml]
----
apis:
  - "com.enonic.app.guillotine:graphql"
----

The API is then available at `/site/<project>/<branch>/<site-path>/_/com.enonic.app.guillotine:graphql`, with project and branch taken from the URL.

== Enonic Cloud / Kubernetes

When using Enonic's https://console.enonic.com/[self-service hosting^] (or the https://developer.enonic.com/docs/kubernetes-operator-for-xp[Enonic K8s Operator^]), expose the API publicly by creating an Ingress.

In your Ingress, specify the target as `/api/com.enonic.app.guillotine:graphql`.

If the Ingress is `example.com/graphql`, you will now be able to access the API on `example.com/graphql`, and select project and branch in the query as described above.

== Using Vhosts

For other hosting options, you may expose the API on custom domains or URLs using vhosts:

.Example - mapping the API to myapi.com
[source,properties]
----
mapping.my-api.host = myapi.com
mapping.my-api.source = /
mapping.my-api.target = /api/com.enonic.app.guillotine:graphql
----

.Example - mapping the API to example.com/graphql
[source,properties]
----
mapping.example-api.host = example.com
mapping.example-api.source = /graphql
mapping.example-api.target = /api/com.enonic.app.guillotine:graphql
----

For more details about vhosts, check out the https://developer.enonic.com/docs/platform/stable/config/vhosts[Platform documentation]
