// This is a value, do not add declare.
export enum InputTypeName {
	AggregationInput = 'AggregationInput',
	BooleanDSLExpressionInput = 'BooleanDSLExpressionInput',
	DSLExpressionValueInput = 'DSLExpressionValueInput',
	DateHistogramAggregationInput = 'DateHistogramAggregationInput',
	DateRangeAggregationInput = 'DateRangeAggregationInput',
	DateRangeInput = 'DateRangeInput',
	ExistsDSLExpressionInput = 'ExistsDSLExpressionInput',
	FulltextDSLExpressionInput = 'FulltextDSLExpressionInput',
	GeoDistanceAggregationInput = 'GeoDistanceAggregationInput',
	GeoPointInput = 'GeoPointInput',
	GeoPointSortDslInput = 'GeoPointSortDslInput',
	HighlightInputType = 'HighlightInputType',
	HighlightPropertiesInputType = 'HighlightPropertiesInputType',
	InDSLExpressionInput = 'InDSLExpressionInput',
	LikeDSLExpressionInput = 'LikeDSLExpressionInput',
	MatchAllDSLExpressionInput = 'MatchAllDSLExpressionInput',
	MaxAggregationInput = 'MaxAggregationInput',
	MinAggregationInput = 'MinAggregationInput',
	NgramDSLExpressionInput = 'NgramDSLExpressionInput',
	NumberRangeInput = 'NumberRangeInput',
	PathMatchDSLExpressionInput = 'PathMatchDSLExpressionInput',
	ProcessHtmlInput = 'ProcessHtmlInput',
	QueryDSLInput = 'QueryDSLInput',
	RangeAggregationInput = 'RangeAggregationInput',
	RangeDSLExpressionInput = 'RangeDSLExpressionInput',
	SortDslInput = 'SortDslInput',
	StatsAggregationInput = 'StatsAggregationInput',
	StemmedDSLExpressionInput = 'StemmedDSLExpressionInput',
	TermDSLExpressionInput = 'TermDSLExpressionInput',
	TermsAggregationInput = 'TermsAggregationInput',
	ValueCountAggregationInput = 'ValueCountAggregationInput',
}

export declare type InputTypeNames = keyof typeof InputTypeName
