name: Generate Documentation

on:
  push:
    branches:
      - "master"
      - "docs-7.1"
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: enonic/release-tools/generate-docs@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-secret: ${{ secrets.DEVELOPER_PORTAL_WEBHOOK_SECRET }}
